language: php
php:
  - 5.3.3
  - 5.4
  - 5.5

before_script:
  - mkdir --mode=777 --parents tests/temp
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit tests/

after_script:
  - rm -R tests/temp/